books/urls.py
from django.conf.urls import url
from django.urls import include,path
from django.views.generic import RedirectView
from .views import index,get_api

urlpatterns = [
    path('',index, name='books'),
    path('api/',get_api,name='api')
]

hope/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bio/', include(('main.urls','main'),namespace='main')),
    path('books/', include(('books.urls','books'),namespace='books')),
    path('register/',include(('story10.urls','story10'),namespace='story10')),
    path('',include(('login.urls','login'),namespace='login')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

login/urls.py
from django.conf.urls import url
from django.urls import include,path
from django.views.generic import RedirectView
from .views import index

urlpatterns = [
    path('',index, name='login')
]

main/urls.py
from django.conf.urls import url
from django.urls import include,path
from django.views.generic import RedirectView
from .views import index

urlpatterns = [
    path('',index, name='main')
]

story10/urls.py
from django.conf.urls import url
from django.urls import include,path
from django.views.generic import RedirectView
from .views import index,post

urlpatterns = [
    path('',index, name='story10'),
    path('signup/',post,name='post')
]

books/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

story10/models.py
from django.db import models

# Create your models here.
class Account(models.Model):
    name = models.CharField(max_length=60)
    email = models.CharField(max_length=60)
    password = models.CharField(max_length=20)

story10/forms.py
from django import forms

class Subscribe_Form(forms.Form):
    name = forms.CharField(label='name',required=True, max_length=60)
    email=forms.EmailField(required=True)
    password=forms.CharField(label='password',required=True, max_length=20)

books/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests

# Create your views here.
response={}

def index(request):
    return render(request,'books.html',response)

def get_api(request):
    url="https://www.googleapis.com/books/v1/volumes?q=quilting"
    json_page = requests.get(url).json()
    return JsonResponse(json_page)

login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.
response = {}

def index(request):
    return render(request,'login.html',response)

def redirect(request):
    return HttpResponseRedirect('/books/')

main/views.py
from django.shortcuts import render
from django.http import JsonResponse

# Create your views here.
response={}

def index(request):
    return render(request,'main.html',response)

story10/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from .models import Account
# Create your views here.
response={}

def index(request):
    return render(request,'register.html',response)

def post(request):
    if (request.method == "POST"):
        response['name'] = request.POST['name']
        response['email'] = request.POST['email']
        response['password'] = request.POST['password']
        acc = Account(name=response['name'],email=response['email'],password=response['password'])
        acc.save()
        
    else:
        print("Hello")
    
    return HttpResponseRedirect('/books/')

books/templates/books.html
{% load staticfiles %} {% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>idk im just really tired</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href=" {% static 'css/books.css' %} " />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script src="{% static 'js/books.js' %}"></script>
</head>

<body>      
    <nav>
        <div class="nav-wrapper">
          <form>
            <div class="input-field">
              <input id="search" type="search" required>
              <label class="label-icon" for="search"><i class="material-icons">search</i></label>
              <i class="material-icons">close</i>
            </div>
          </form>
        </div>
      </nav>
    <div class="container">
        
        <div id="favCount">

          </div>
    </div>
    <a href="/" onclick="signOut();">Sign out</a>
    <script>
      function signOut() {
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signOut().then(function () {
          console.log('User signed out.');
        });
      }
    </script>
</body>

</html>

login/templates/login.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="google-signin-client_id" content="901165450315-b9q1okni8phrcqotibavn6en88ap0m3h.apps.googleusercontent.com">

    <title>Home</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
     <!-- Compiled and minified CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> 
    <link href="https://fonts.googleapis.com/css?family=Archivo+Black" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/login.css' %}"/>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
    
    <script src="{% static 'js/login.js' %}"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
</head>
<body>
    <div class="container">
        <div class="intro block center">
            Welcome
        </div>
        <div class="menu">
            <a class="btn btn-light" href="/register/" role="button">Sign up</a>
           <div class="g-signin2" data-onsuccess="onSignIn">
           </div>
        </div>
        
    </div>
</body>
</html>

main/templates/main.html
{% load staticfiles %} {% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hello</title>
    <link rel="icon" href="https://cdn130.picsart.com/267178871004211.png?r1024x1024">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href=" {% static 'css/main.css' %} " />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script src="{% static 'js/main.js' %}"></script>
</head>

<body onload="myFunction()" style="margin:0;">
    <div id="loader"></div>
    <div class="container" style="display:none;" id="myDiv" class="animate-bottom">
        <div>
            <h6 id="theme-header">Page Theme</h6>

            <!-- Switch -->
            <div class="switch">
                <label>
                    Light
                    <input type="checkbox">
                    <span class="lever"></span>
                    Dark
                </label>
            </div>
        </div>

        <!--Accordion-->
        <div id="accordion">
            <h3>Activities</h3>
            <div>
                <p>sleep and chill</p>
            </div>
            <h3>Organization Experience</h3>
            <div>
                <ul>
                    <li>Ketua Kaderisasi Subseksi Kemasyarakatan SMAN 8 Jakarta</li>
                    <li>Staf Biro Bisnis dan Kemitraan BEM Fasilkom UI 2018</li>
                </ul>
            </div>
            <h3>Achievements</h3>
            <div>
                <p>404</p>
                <ul>
                    <li>:(</li>
                    <li>:(</li>
                    <li>:(</li>
                </ul>
            </div>
        </div>
        <a href="/books/" class="btn">A Button for Books!</a>
    </div>
</body>

</html>

story10/templates/register.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Subscribe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/register.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> 
    
    <!-- <script src="main.js"></script> -->
</head>
<body>
    
    <form action="{% url 'story10:post' %}" method="POST" id="testform">
            {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputName1">Name</label>
            <input type="name" class="form-control-sm" id="exampleInputName1" placeholder="Name" name="name">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control-sm" id="exampleInputPassword1" placeholder="Password" name="password">
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button class = "btn btn-primary" value= "submit">Submit</button>
        <!-- <a class="btn btn-primary">Submit</a> -->
    </form>
</body>
</html>